# Generated by Django 4.2.14 on 2024-09-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_otp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="otp",
            old_name="user",
            new_name="email",
        ),
        migrations.AddField(
            model_name="otp",
            name="phone",
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
