# Generated by Django 4.2.14 on 2024-10-04 04:14

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogAdditionalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_images",
                    models.ImageField(blank=True, null=True, upload_to="blog-images"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("author", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog-images"),
                ),
                ("date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CancelBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_id", models.IntegerField(unique=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Patient Requested", "Patient Requested"),
                            ("Doctor Not Available", "Doctor Not Available"),
                            ("Other", "Other"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "refund",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("No Refund", "No Refund"),
                            ("Refund Applicable", "Refund Applicable"),
                            ("Refund Processing", "Refund Processing"),
                            ("Refund Completed", "Refund Completed"),
                        ],
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dept_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=5,
                        max_length=10,
                        prefix="dept",
                        unique=True,
                    ),
                ),
                ("dept_name", models.CharField(max_length=50, unique=True)),
                ("dept_description", models.CharField()),
                (
                    "dept_image",
                    models.ImageField(blank=True, null=True, upload_to="dept_images/"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
