# Generated by Django 4.2.14 on 2024-10-04 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0002_initial"),
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancelbooking",
            name="cancelled_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cancelbooking",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="doctors.doctor"
            ),
        ),
        migrations.AddField(
            model_name="cancelbooking",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.patient",
            ),
        ),
        migrations.AddField(
            model_name="blogadditionalimage",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_images",
                to="adminapp.blogs",
            ),
        ),
    ]
