# Generated by Django 4.2.14 on 2024-09-17 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0022_remove_patient_allergies_remove_patient_diagnosis_and_more"),
        ("adminapp", "0005_blogs_blogadditionalimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancelbooking",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.patient",
            ),
        ),
    ]
