# Generated by Django 4.2.14 on 2024-10-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        blank=True,
                        choices=[("Morning", "Morning"), ("Evening", "Evening")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("isAvailable", models.BooleanField(default=True)),
                ("online_consultation", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="BlackListedToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField()),
                ("blacklisted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[("Morning", "Morning"), ("Evening", "Evening")]
                    ),
                ),
                ("time_slot", models.TimeField()),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[("Direct", "Direct"), ("Razor Pay", "Razor Pay")],
                        max_length=10,
                    ),
                ),
                ("booked_day", models.DateField()),
                ("date_of_booking", models.DateField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "booking_status",
                    models.CharField(
                        choices=[("Booked", "Booked"), ("Cancelled", "Cancelled")],
                        default="Booked",
                    ),
                ),
                (
                    "consultation_mode",
                    models.CharField(
                        choices=[("Offline", "Offline"), ("Online", "Online")],
                        default="Offline",
                    ),
                ),
            ],
        ),
    ]
