# Generated by Django 4.2.14 on 2024-10-04 04:14

import datetime
from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "customuser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doc_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=5,
                        max_length=10,
                        prefix="doc",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("is_HOD", models.BooleanField(default=False)),
                (
                    "doc_image",
                    models.ImageField(blank=True, null=True, upload_to="doc_images/"),
                ),
                ("account_activated", models.BooleanField(default=False)),
                ("description", models.CharField(blank=True, null=True)),
                ("is_doctor", models.BooleanField(default=False)),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("200.00"), max_digits=10
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to="adminapp.department",
                        to_field="dept_id",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("users.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="DoctorRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("message", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="EveningSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startTime", models.TimeField(default=datetime.time(14, 0))),
                ("endTime", models.TimeField(default=datetime.time(18, 0))),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MorningSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startTime", models.TimeField(default=datetime.time(9, 0))),
                ("endTime", models.TimeField(default=datetime.time(13, 0))),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField()),
                ("title", models.CharField(default="Sick Leave")),
                ("is_seen", models.BooleanField(default=False)),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=5,
                        max_length=10,
                        prefix="pat",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=25, unique=True)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Female", "Female"),
                            ("Male", "Male"),
                            ("Other", "Other"),
                        ],
                        default="Male",
                        null=True,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ManyToManyField(
                        blank=True, related_name="doctor", to="doctors.doctor"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "user")},
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="booked_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.doctor",
                to_field="doc_id",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.patient",
                to_field="name",
            ),
        ),
        migrations.AddField(
            model_name="availability",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.doctor",
                to_field="doc_id",
            ),
        ),
        migrations.AddField(
            model_name="availability",
            name="evening",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.eveningslot",
            ),
        ),
        migrations.AddField(
            model_name="availability",
            name="morning",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.morningslot",
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=5,
                        max_length=10,
                        prefix="rep",
                        unique=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("allergies", models.TextField(blank=True, default="NA", null=True)),
                ("symptoms", models.TextField(blank=True, null=True)),
                ("diagnosis", models.TextField(blank=True, default="NA", null=True)),
                ("report_date", models.DateField(auto_now_add=True)),
                ("medications", models.TextField(blank=True, default="NA", null=True)),
                (
                    "family_history",
                    models.TextField(blank=True, default="NA", null=True),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.patient",
                    ),
                ),
            ],
            options={
                "unique_together": {("report_date", "doctor", "patient")},
            },
        ),
        migrations.CreateModel(
            name="LeaveApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("Sick Leave", "Sick Leave"),
                            ("Vacation Leave", "Vacation Leave"),
                            ("Personal Leave", "Personal Leave"),
                            ("Maternity Leave", "Maternity Leave"),
                            ("Paternity Leave", "Paternity Leave"),
                            ("Bereavement Leave", "Bereavement Leave"),
                        ],
                        default="Sick Leave",
                    ),
                ),
                ("leave_start_date", models.DateField()),
                ("leave_end_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True, null=True, upload_to="leave_documents/"
                    ),
                ),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.doctor",
                    ),
                ),
            ],
            options={
                "unique_together": {("doctor", "submission_date")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("booked_day", "patient", "doctor", "booking_status")},
        ),
        migrations.AlterUniqueTogether(
            name="availability",
            unique_together={("day_of_week", "doctor")},
        ),
    ]
