# Generated by Django 4.2.14 on 2024-10-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="doc_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="doc_phone",
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
