# Generated by Django 4.2.14 on 2024-10-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_doctor_doc_email_doctor_doc_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
