# Generated by Django 4.2.14 on 2024-09-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0020_delete_blogadditionalimage_delete_blogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="slot",
            field=models.CharField(
                choices=[("Morning", "Morning"), ("Evening", "Evening")],
                default="Morning",
            ),
            preserve_default=False,
        ),
    ]
