# Generated by Django 4.2.14 on 2024-09-17 05:26

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0021_booking_slot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="diagnosis",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="height",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="symptoms",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="weight",
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=5,
                        max_length=10,
                        prefix="rep",
                        unique=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("allergies", models.TextField(blank=True, null=True)),
                ("symptoms", models.TextField(blank=True, null=True)),
                ("diagnosis", models.TextField(blank=True, null=True)),
                ("report_date", models.DateField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.patient",
                    ),
                ),
            ],
        ),
    ]
