# Generated by Django 4.2.14 on 2024-09-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0022_remove_patient_allergies_remove_patient_diagnosis_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("booked_day", "patient", "doctor", "booking_status")},
        ),
    ]
