# Generated by Django 4.2.14 on 2024-09-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0023_alter_booking_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="availability",
            name="online_consultation",
            field=models.BooleanField(default=False),
        ),
    ]
