# Generated by Django 4.2.14 on 2024-09-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0024_availability_online_consultation"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="consultation_mode",
            field=models.CharField(
                choices=[("Offline", "Offline"), ("Online", "Online")],
                default="Offline",
            ),
        ),
    ]
