# Generated by Django 4.2.14 on 2024-09-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0025_booking_consultation_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="family_history",
            field=models.CharField(blank=True, default="NA", max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="medications",
            field=models.TextField(blank=True, default="NA", null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="allergies",
            field=models.TextField(blank=True, default="NA", null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="diagnosis",
            field=models.TextField(blank=True, default="NA", null=True),
        ),
    ]
