# Generated by Django 4.2.14 on 2024-09-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0026_report_family_history_report_medications_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="family_history",
            field=models.CharField(blank=True, default="NA", null=True),
        ),
    ]
