# Generated by Django 4.2.14 on 2024-09-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0027_alter_report_family_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="family_history",
            field=models.TextField(blank=True, default="NA", null=True),
        ),
    ]
