# Generated by Django 4.2.14 on 2024-09-20 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0028_alter_report_family_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="doctors.patient"
            ),
        ),
    ]
