# Generated by Django 4.2.14 on 2024-09-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0029_alter_report_patient"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Report",
        ),
    ]
