# Generated by Django 4.2.14 on 2024-09-20 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0031_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="doctor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctors.doctor",
            ),
            preserve_default=False,
        ),
    ]
