# Generated by Django 4.2.14 on 2024-09-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0032_report_doctor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="doctor",
        ),
    ]
