# Generated by Django 4.2.14 on 2024-09-22 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0034_report_doctor"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="report",
            unique_together={("report_date", "doctor", "patient")},
        ),
        migrations.CreateModel(
            name="LeaveApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("Sick Leave", "Sick Leave"),
                            ("Vacation Leave", "Vacation Leave"),
                            ("Personal Leave", "Personal Leave"),
                            ("Maternity Leave", "Maternity Leave"),
                            ("Paternity Leave", "Paternity Leave"),
                            ("Bereavement Leave", "Bereavement Leave"),
                        ],
                        default="Sick Leave",
                    ),
                ),
                ("leave_start_date", models.DateField()),
                ("leave_end_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True, null=True, upload_to="leave_documents/"
                    ),
                ),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.doctor",
                    ),
                ),
            ],
        ),
    ]
