# Generated by Django 4.2.14 on 2024-09-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0035_alter_report_unique_together_leaveapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField()),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("Sick Leave", "Sick Leave"),
                            ("Vacation Leave", "Vacation Leave"),
                            ("Personal Leave", "Personal Leave"),
                            ("Maternity Leave", "Maternity Leave"),
                            ("Paternity Leave", "Paternity Leave"),
                            ("Bereavement Leave", "Bereavement Leave"),
                        ],
                        default="Sick Leave",
                    ),
                ),
            ],
        ),
    ]
