# Generated by Django 4.2.14 on 2024-09-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0036_notification"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="leaveapplication",
            unique_together={("doctor", "submission_date")},
        ),
    ]
