# Generated by Django 4.2.14 on 2024-09-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0037_alter_leaveapplication_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
