# Generated by Django 4.2.14 on 2024-09-22 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0038_notification_is_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=datetime.datetime(2024, 9, 22, 0, 0)
            ),
            preserve_default=False,
        ),
    ]
