# Generated by Django 4.2.14 on 2024-09-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0039_notification_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(default="Sick Leave"),
        ),
    ]
