# Generated by Django 4.2.14 on 2024-09-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0040_alter_notification_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
