# Generated by Django 4.2.14 on 2024-10-01 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0006_cancelbooking_patient"),
        ("doctors", "0042_alter_patient_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctors",
                to="adminapp.department",
                to_field="dept_id",
            ),
        ),
    ]
